language: go

go:
  - 1.4
  - tip

services:
  - redis-server
  - rabbitmq

before_script:
  - rabbitmqctl add_vhost /test
  - rabbitmqctl set_permissions -p /test guest ".*" ".*" ".*"

script: go test ./...